---
- name: run backup and upload to SFTP
  hosts: all
  gather_facts: no
  connection: network_cli
  
  pre_tasks:
    - name: Generate timestamp once
      include_tasks: tasks/t_time_stamp.yml
      args:
        apply:
          delegate_to: localhost
      run_once: true
      
    - name: set file name
      set_fact:
        filename: "{{ ansible_network_hostname | default(inventory_hostname) }}_{{ timestamp_sec }}.txt
      run_once: true  
  
    - name: show result
      debug:
        msg: "{{ filename }}"
      
    - name: add SFTP server to inventory
      include_tasks: tasks/t_SFTP.yml
      args:
        apply:
          delegate_to: localhost
      run_once: true
      
  tasks:
    - name: run backup
      cli_config:
        backup: yes
        backup_options:
          filename: "{{ filename }}"
          dir_path: /tmp/tmpfiles
#        when:
#          - ansible_connection == 'network_cli'
      register: backup_outputs
      
    - name: Create backup folder
      ansible.builtin.file:
        path: "{{ sftp_path }}/{{ timestamp_day }}"
        state: directory
        mode: "755"
      run_once: true
      delegate_to: sftp_target
      
    - name: upload to SFTP
      copy:
        src: "/tmp/tmpfiles/{{ filename }}"
        dest: "{{ sftp_path }}/{{ timestamp_day }}/{{ filename }}"
        mode: "0444"
      delegate_to: sftp_target
      no_log: flase
    - name: delete tmp file
      file:
        path: "/tmp/tmpfiles/{{ timestamp_day }}"
        state: absent
      delegate_to: localhost
