---
- name: run backup and upload to SFTP
  hosts: all
  gather_facts: no
  connection: network_cli
  
  pre_tasks:
    - name: Generate timestamp once
      import_tasks: tasks/t_time_stamp.yml
      delegate_to: localhost
      run_once: true
      
    - name: set file name
      set_fact:
        filename: "{{ ansible_network_hostname | default(inventory_hostname) }}_{{ timestamp_sec }}.txt"
  
    - name: show result
      debug:
        msg: "{{ filename }}.txt"
      
    - name: add SFTP server to inventory
      import_task: tasks/t_SFTP.yml
      delegate_to: localhost
      run_once: true
      
  tasks:
    - name: run backup
      cli_config:
        backup: yes
        backup_options:
          filename: "{{ filename }}"
          dir_path: /tmp/tmpfiles
        when:
          - ansible_connection == 'network_cli'
      register: backup_outputs
      
    - name: Create backup folder
      
    - name: upload to SFTP
      import_task: tasks/t_upload.yml
      delegate_to: sftp_target
      
    - name: delete tmp file
      file:
        path: "/tmp/tmpfiles/{{ filename }}"
        state: absent
      delegate_to: localhost
      run_once: true
