---
- name: save config first
  import_playbook: save_config.yml
  
- name: run backup and upload to SFTP
  hosts: all
  gather_facts: no
  connection: network_cli
  
  pre_tasks:
    - name: Generate timestamp once
      import_tasks: tasks/t_time_stamp.yml
      delegate_to: localhost
      run_once: true
      
    - name: set file name
      set_fact:
        filename: "{{ ansible_network_hostname | default(inventory_hostname) }}_{{ timestamp_sec }}.txt"

    - name: add SFTP server to inventory
      import_tasks: tasks/t_SFTP.yml
      delegate_to: localhost
      run_once: true

    - name: Create backup folder
      import_tasks: tasks/t_create_folder.yml
      run_once: true
      delegate_to: sftp_target
      
  tasks:
    - name: run backup
      cli_config:
        backup: yes
        backup_options:
          filename: "{{ filename }}"
          dir_path: /tmp/tmpfiles
      register: backup_outputs
            
    - name: upload backup file to SFTP server
      import_tasks: tasks/t_upload.yml
      delegate_to: sftp_target    
      
  post_tasks:
    - name: delete tmp file
      import_tasks: tasks/t_delete_file.yml
      delegate_to: localhost
      run_once: true
