---
- name: upload firmware
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - ansible.netcommon
    
  pre_tasks:
    - name: Ensure scp library is installed on the control node
      ansible.builtin.pip:
        name: scp
      delegate_to: localhost

    - name: add SFTP server to inventory
      import_tasks: tasks/t_SFTP.yml
      delegate_to: localhost
      run_once: true

  tasks:      
    - name: Download firmware from SFTP host to controller
      ansible.builtin.fetch:
        src: "{{ sftp_path }}/{{ filename }}"
        dest: "/tmp/{{ firmware }}"
        flat: true
      delegate_to: sftp_target
      run_once: true

    - name: Upload firmware to switch
      net_put:
        src: "/tmp/{{ filename }}"
        dest: "{{ firmware }}"
        
  post_tasks:        
    - name: delete firmware from temp file space
      import_tasks: tasks/t_delete_file.yml
      run_once: true
      delegate_to: localhost

    - name: Verify file exists and size
      cli_command:
        command: "dir | include {{ filename }}"
      register: verify

    - name: Check if file is uploaded
      assert:
      that:
        - verify.stdout is search(filename)
      fail_msg: "Firmware file missing"
