---
- name: upload firmware
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - ansible.netcommon
      
  pre_tasks:
    - name: Ensure scp library is installed on the control node
      ansible.builtin.pip:
        name: scp
      delegate_to: localhost
      run_once: true

    - name: add SFTP server to inventory
      import_tasks: tasks/t_SFTP.yml
      delegate_to: localhost
      run_once: true

  tasks:      
    - name: Download firmware from SFTP host to controller
      ansible.builtin.fetch:
        src: "{{ sftp_path }}/{{ filename }}"
        dest: "/tmp/tmpfiles/{{ filename }}"
        flat: true
      delegate_to: sftp_target
      run_once: true

    - name: Upload firmware to switch
      net_put:
        src: "/tmp/tmpfiles/{{ filename }}"
        dest: "{{ filename }}"
      vars:
        ansible_command_timeout: 3600  # 1小时
        
  post_tasks:        
    - name: delete firmware from temp file space
      import_tasks: tasks/t_delete_file.yml
      run_once: true
      delegate_to: localhost

    - name: Verify file md5
      import_tasks: tasks/t_md5_cal.yml
      register: md5_output
      
    - name: Compare with official MD5
      import_tasks: tasks/t_md5_check.yml
