---
- name: upload firmware
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - ansible.netcommon
  vars:
    md5_commands:
      ios: "verify /md5 {{ filename }}"
      nxos: "show file {{ filename }} md5sum"
      
  pre_tasks:
    - name: Ensure scp library is installed on the control node
      ansible.builtin.pip:
        name: scp
      delegate_to: localhost

    - name: add SFTP server to inventory
      import_tasks: tasks/t_SFTP.yml
      delegate_to: localhost
      run_once: true

  tasks:      
    - name: Download firmware from SFTP host to controller
      ansible.builtin.fetch:
        src: "{{ sftp_path }}/{{ filename }}"
        dest: "/tmp/{{ firmware }}"
        flat: true
      delegate_to: sftp_target
      run_once: true

    - name: Upload firmware to switch
      net_put:
        src: "/tmp/{{ filename }}"
        dest: "{{ firmware }}"
        
  post_tasks:        
    - name: delete firmware from temp file space
      import_tasks: tasks/t_delete_file.yml
      run_once: true
      delegate_to: localhost

    - name: Verify file md5
      cli_command:
        command: "{{ md5_commands[ansible_network_os] }}"
      register: md5_output
      
    - name: Compare with official MD5
      assert:
        that:
          - md5 | lower in md5_output.stdout | lower
        fail_msg: |
          MD5 mismatch on {{ ansible_network_hostname | default(inventory_hostname) }}!
          Expected: {{ md5 }}
          Output: {{ md5_output.stdout }}
        success_msg: "MD5 verified on {{ ansible_network_hostname | default(inventory_hostname) }}"
