---
- name: Run Backup first
  import_playbook: backup.yml

- name: Firmware upgrade workflow
  hosts: all
  gather_facts: no
  connection: network_cli
  
  pre_tasks:
    - name: Verify file md5
      import_tasks: tasks/t_md5_cal.yml
      register: md5_output
      
    - name: Compare with official MD5
      import_tasks: tasks/t_md5_check.yml

  tasks:
    - name: Upgrade standalone devices
      block:
        - name: Install
          import_tasks: tasks/t_patch.yml
          
        - name: print install result
          debug: 
            msg: "{{  install_output  }}"
            
        - name: confirm standalone upgrade is complete
          import_tasks: tasks/t_patch_confirm.yml
      when: patch_tag == "standalone"

    - name: Upgrade primary devices
      when: patch_tag == "primary"
      debug:
        msg:{  {ansible_network_hostname  }} + {{  patch_tag  }}      
        
#    - name: confirm primary upgrade is complete
#      when: patch_tag == "primary"
#      import_tasks: tasks/t_upgrade_confirm.yml
      
    - name: Upgrade secondary devices
      when: patch_tag == "primary"
      debug:
        msg:{  {ansible_network_hostname  }} + {{  patch_tag  }}
        
#    - name: confirm secondary upgrade is complete
#      when: patch_tag == "secondary"
#      import_tasks: tasks/t_upgrade_confirm.yml
