---
#- name: Run Backup first
#  import_playbook: backup.yml

- name: Firmware upgrade workflow
  hosts: all
  gather_facts: no
  connection: network_cli
  
  pre_tasks:
    - name: get expected version
      set_fact:
        file_version: "{{ firmware_filename | regex_search('(\\d+\\.\\d+\\.\\d+)') }}"
      run_once: true
      delegate_to: localhost
      
    - name: debug verion
      debug: 
        msg: "{{ file_version  }}"
        
    - name: Verify file md5
      import_tasks: tasks/t_check_md5.yml

  tasks:
    - name: Upgrade standalone devices
      block:
        - name: Install
          import_tasks: tasks/t_patch.yml
            
        - name: confirm standalone upgrade is complete
          import_tasks: tasks/t_patch_confirm.yml
      when: patch_tag == "standalone"
      
    - name: Upgrade primary devices
      block:
        - name: Install
          import_tasks: tasks/t_patch.yml
            
        - name: confirm primary upgrade is complete
          import_tasks: tasks/t_patch_confirm.yml
      when: patch_tag == "primary"

    - name: Upgrade secondary devices
      block:
        - name: Install
          import_tasks: tasks/t_patch.yml
            
        - name: confirm secondary upgrade is complete
          import_tasks: tasks/t_patch_confirm.yml
      when: patch_tag == "secondary"
