---
#- name: Run Backup first
#  import_playbook: backup.yml

- name: pre-run
  hosts: localhost
  serial: 10
  gather_facts: no
  tasks:
    - name: get expected version
      set_fact:
        file_version: "{{ firmware_filename | regex_search('(\\d+\\.\\d+\\.\\d+)') }}"
      run_once: true
      delegate_to: localhost

    - name: debug version
      debug:
        msg: "{{  file_version  }}"
      run_once: true

- name: Upgrade secondary devices
  hosts: "even:&ios"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_check_md5_ios.yml
    - import_tasks: tasks/t_patch_install_ios.yml
#    - import_tasks: tasks/t_patch_confirm.yml

- name: Upgrade primary devices
  hosts: "odd:&ios"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_check_md5_ios.yml
    - import_tasks: tasks/t_patch_install_ios.yml
#    - import_tasks: tasks/t_patch_confirm.yml

- name: Post patch cleanup
  hosts: "even:&odd:&ios"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_patch_clean_ios.yml
