---
#- name: Run Backup first
#  import_playbook: backup.yml

- name: pre-work
  hosts: localhost
  tasks:
  - name: create fresh log file
    copy:
      content: ""
      dest: "/tmp/tmpfiles/patch_log.txt"
      force: yes
    delegate_to: localhost

- name: Upgrade even device group
  hosts: "even:&nxos"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_patch_nxos.yml

- name: Upgrade odd device group
  hosts: "odd:&nxos"
  serial: 10
  gather_facts: no
  connection: network_cli
  collections:
    - ansible.utils
  tasks:
    - import_tasks: tasks/t_patch_nxos.yml

#- name: Post patch cleanup
#  hosts: "all:!temp"
#  serial: 10
#  gather_facts: no
#  connection: network_cli
#  tasks:
#    - import_tasks: tasks/t_patch_clean_nxos.yml
