---
- name: Run Backup first
  import_playbook: backup.yml

- name: Build patch groups
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: get expected version
      set_fact:
        file_version: "{{ firmware_filename | regex_search('(\\d+\\.\\d+\\.\\d+)') }}"
      run_once: true
      delegate_to: localhost
      
    - name: debug version
      debug: 
        msg: "{{ file_version  }}"
      run_once: true
      
- name: Upgrade standalone devices
  hosts: "all:!even:!odd"
  gather_facts: no
  connection: network_cli
  tasks:
#    - import_tasks: tasks/t_check_md5.yml
    - import_tasks: tasks/t_patch_install.yml
#    - import_tasks: tasks/t_patch_confirm.yml

- name: Upgrade secondary devices
  hosts: even
  gather_facts: no
  connection: network_cli
  tasks:
#    - import_tasks: tasks/t_check_md5.yml
    - import_tasks: tasks/t_patch_install.yml
#    - import_tasks: tasks/t_patch_confirm.yml
    
- name: Upgrade primary devices
  hosts: odd
  gather_facts: no
  connection: network_cli
  tasks:
 #   - import_tasks: tasks/t_check_md5.yml
    - import_tasks: tasks/t_patch_install.yml
 #   - import_tasks: tasks/t_patch_confirm.yml

- name: Post patch cleanup
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: t_patch_clean.yml