---
#- name: Run Backup first
#  import_playbook: backup.yml

- name: Upgrade even device group
  hosts: "even:&nxos"
  serial: 10
  gather_facts: no
  connection: network_cli
  pre_tasks:
    - import_tasks: tasks/t_time_stamp.yml
    - name: interface status check before patch
      cli_command:
        command: "show interface status"
      register: int_status_output

    - name: set filename for interface status
      set_fact:
        filename: "{{ ansible_network_hostname }}_{{ timestamp_sec }}_if.txt"

    - name: save to local file
      copy:
        content: "{{ int_status_output.stdout }}"
        dest: "/tmp/tmpfiles/{{ filename }}"

    - import_tasks: tasks/t_upload.yml
#    - import_tasks: tasks/t_check_md5_nxos.yml
#    - import_tasks: tasks/t_patch_install_nxos.yml
#    - import_tasks: tasks/t_patch_confirm.yml

- name: Upgrade odd device group
  hosts: "odd:&nxos"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
#    - import_tasks: tasks/t_check_md5_nxos.yml
#    - import_tasks: tasks/t_patch_install_nxos.yml
#    - import_tasks: tasks/t_patch_confirm.yml

#- name: Post patch cleanup
#  hosts: "even:&odd:&nxos"
#  serial: 10
#  gather_facts: no
#  connection: network_cli
#  tasks:
#    - import_tasks: tasks/t_patch_clean_nxos.yml
