---
- name: Run Backup first
  import_playbook: backup.yml

- name: Upgrade secondary devices
  hosts: "even:&nxos"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_check_md5_nxos.yml
    - import_tasks: tasks/t_patch_install_nxos.yml
    - import_tasks: tasks/t_patch_confirm.yml

- name: Upgrade primary devices
  hosts: "odd:&nxos"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_check_md5_nxos.yml
    - import_tasks: tasks/t_patch_install_nxos.yml
    - import_tasks: tasks/t_patch_confirm.yml

#- name: Post patch cleanup
#  hosts: "even:&odd:&nxos"
#  serial: 10
#  gather_facts: no
#  connection: network_cli
#  tasks:
#    - import_tasks: tasks/t_patch_clean_nxos.yml
