---
- name: Run Backup first
  import_playbook: backup.yml

- name: pre-work
  hosts: "all:!temp"
  gather_facts: no
  tasks:
  - name: create fresh log file
    copy:
      content: ""
      dest: "/tmp/tmpfiles/patch_log.txt"
      force: yes
    delegate_to: localhost
    run_once: true

  - name: Set switch to load start-up configuration while booting
    ios_config:
      lines:
        - no system ignore startupconfig switch all
      save_when: always
    register: config_output
    ignore_error: true

- name: Upgrade even devices
  hosts: "even:&ios"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_patch_ios.yml

- name: Upgrade odd devices
  hosts: "odd:&ios"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_patch_ios.yml

- name: Post patch cleanup
  hosts: "all:!temp"
  serial: 10
  gather_facts: no
  connection: network_cli
  tasks:
    - import_tasks: tasks/t_patch_clean_ios.yml
