- name: Manage Controller inventory hosts
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "https://{{ controller_IP }}"
    controller_token: "{{ lookup('env','TOWER_TOKEN') }}"
    inventory_name: "HK_Switches"
    hosts_to_add:
      - name: sw01
        ansible_host: 10.0.0.1
        ansible_network_os: nxos
#        groups: ["network_devices", "patch_even"]
      - name: sw02
        ansible_host: 10.0.0.2
        ansible_network_os: ios
#        groups: ["network_devices", "patch_odd"]
  tasks:
    - name: Who am I
      uri:
        url: "{{ tower_host }}/api/v2/me/"
        method: GET
        headers:
          Authorization: "Bearer {{ tower_token }}"
        validate_certs: no
      register: me
    - debug:
        var: me.json
