- name: Import/Update hosts + groups in Tower inventory from CSV (IP as host name)
  hosts: localhost
  gather_facts: false

  vars:
    controller_host: "https://{{ host }}"
    controller_token: "{{ oauth_token }}"
    csv_file: hosts.csv

  tasks:
    - debug:
        msg:
          "{{ host }}"
    - name: Get inventory_id from Tower job context
      set_fact:
        inventory_id: "{{ tower_inventory_id }}"
      run_once: true

    - name: Read CSV
      read_csv:
        path: "{{ csv_file }}"
      register: csv_data
      run_once: true

    - name: Build unique group list from CSV
      set_fact:
        unique_groups: >-
          {{
            (
              (csv_data.list | map(attribute='groups') | list | join(',')) .split(',')
              | map('regex_replace', '^\\s+|\\s+$', '')
              | reject('equalto', '')
              | list
              | unique
            )
          }}
      run_once: true

    # 1) Ensure groups exist
    - name: Ensure groups exist
      include_tasks: tasks/t_inventory_group_create.yml
      loop: "{{ unique_groups }}"
      loop_control:
        loop_var: group_name

    # 2) Upsert hosts (create or update) by IP (name == IP)
    - name: Upsert hosts from CSV
      include_tasks: tasks/t_inventory_host.yml
      loop: "{{ csv_data.list }}"
      loop_control:
        loop_var: row

    # 3) Associate hosts to groups
    - name: Associate hosts to groups
      include_tasks: tasks/t_inventory_group_asso.yml
      loop: "{{ csv_data.list }}"
      loop_control:
        loop_var: row