- name: Manage Controller inventory hosts
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "https://{{ controller_IP }}"
    controller_token: "{{ controller_token }}"
  tasks:
    - name: Who am I (Tower /api/v2/me/)
      uri:
        url: "{{ controller_host }}/api/v2/me/"
        method: GET
        headers:
          Authorization: "Bearer {{ controller_token }}"
          Content-Type: "application/json"
          Accept: "application/json"
        validate_certs: no
        status_code: 200
        return_content: yes
      register: me

    - name: Print identity result
      debug:
        var: me.json