- name: Manage Controller inventory hosts
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "https://{{ controller_IP }}"
    controller_token: "{{ controller_token }}"
  tasks:

    - name: Lookup inventory ID
      uri:
        url: "{{ controller_host }}/api/v2/inventories/?name={{ inventory_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ controller_token }}"
        validate_certs: no
        return_content: yes
      register: inv_result

    - name: Set inventory_id
      set_fact:
        inventory_id: "{{ inv_result.json.results[0].id }}"
    - name: Add host 1
      uri:
        url: "{{ controller_host }}/api/v2/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ controller_token }}"
          Content-Type: "application/json"
        validate_certs: no
        body_format: json
        body:
          name: "10.10.10.11"
          description: "N9K-LEAF-01"
          inventory: "{{ inventory_id }}"
          variables: |
            ansible_host: 10.10.10.11
            ansible_network_hostname: N9K-LEAF-01
        status_code: 201
      ignore_errors: yes

    - name: Add host 2
      uri:
        url: "{{ controller_host }}/api/v2/hosts/"
        method: POST
        headers:
          Authorization: "Bearer {{ controller_token }}"
          Content-Type: "application/json"
        validate_certs: no
        body_format: json
        body:
          name: "10.10.10.12"
          description: "N9K-LEAF-02"
          inventory: "{{ inventory_id }}"
          variables: |
            ansible_host: 10.10.10.12
            ansible_network_hostname: N9K-LEAF-02
        status_code: 201
      ignore_errors: yes