---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: no
  connection: network_cli

  pre_tasks:
# name: Generate timestamp once
    - import_tasks: tasks/t_time_stamp.yml

    - name: set file name
      set_fact:
        filename: "show_output_{{ timestamp_sec }}"
      delegate_to: localhost
      run_once: true

  tasks:
    - name: run defined command from Extra variables
      cli_command:
        command: "{{ item }}"
      loop: "{{ cli_cmd }}"
      register: cli_outputs
        
    - name: create output file locally
      copy:
        content: |
          =================================================
          Network Command Output Report
          Generated: {{ timestamp_day }} - {{ timestamp_sec }}
          Total Hosts: {{ ansible_play_hosts | length }}
          =================================================
          
          {% for host in ansible_play_hosts %} 

          =================================================
          IP: {{ host }}
          Hostname: {{ hostvars[host].ansible_network_hostname | default("hostname undefined") }}
          {% for result in hostvars[host].cli_outputs.results %} 
          ----------------------------------------
          Command {{ loop.index }}: {{ result.item }}
          ----------------------------------------
          {{ result.stdout }}      
          {% endfor %}
          {% endfor %}
          ========================================
        dest: "/tmp/tmpfiles/{{  filename  }}"
      run_once: true
      delegate_to: localhost

# add SFTP server to inventory
    - import_tasks: tasks/t_sftp.yml
      delegate_to: localhost
      run_once: true

# name: upload backup file to SFTP server
    - import_tasks: tasks/t_upload.yml
      delegate_to: sftp_target
      run_once: true

# No native SFTP in Ansible. Use shell fallback below if needed.
#      shell: |
#        sshpass -p "{{ sftp_password }}" sftp -o StrictHostKeyChecking=no -P {{ sftp_port | default(22) }} {{ sftp_username }}@{{ sftp_host }} <<EOF
#        cd ansible
#        put /tmp/show_output_{{ timestamp_sec }}.txt
#        bye
#        EOF
#      delegate_to: localhost

  post_tasks:
# name: delete tmp file
    - import_tasks: tasks/t_delete_file.yml
      delegate_to: localhost
      run_once: true
      no_log: fals
