- name: run cli command
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
   - name: run defined command from Extra variables
     ios_command:"{{ cli_cmd }}"
     register: cli_output

  - name: show result
    debug:
     var: cli_output.stdout
