---
- name: run cli command
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: test input
      debug:
        var: "{{ cli_cmd }}"
    - name: run defined command from Extra variables
      ios_command:
        commands: "{{ cli_cmd }}"
      register: cli_output

    - name: show result
      debug:
        var: cli_output.stdout
