---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: generate time stamp
      set_fact:
        timestamp_day: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d') }}"
        timestamp_sec: "{{ lookup('pipe','TZ=America/New_York date +%H%M%S') }}"
      run_once: true
      delegate_to: localhost

    - name: debug
      debug:
        msg: "{{ patch_tag }}"

    - name: run defined command from Extra variables
      cli_command:
        command: "{{ item }}"
      loop: "{{ cli_cmd }}"
      register: cli_outputs
        
    - name: create output file locally
      copy:
        content: |
          =================================================
          Network Command Output Report
          Generated: {{ timestamp_day }} - {{ timestamp_sec }}
          Total Hosts: {{ ansible_play_hosts | length }}
          =================================================
          
          {% for host in ansible_play_hosts %} 

          =================================================
          IP: {{ host }}
          Hostname: {{ hostvars[host].ansible_network_hostname | default("hostname undefined") }}
          {% for result in hostvars[host].cli_outputs.results %} 
          ----------------------------------------
          Command {{ loop.index }}: {{ result.item }}
          ----------------------------------------
          {{ result.stdout }}      
          {% endfor %}
          {% endfor %}
          ========================================
        dest: "/tmp/show_output_{{ timestamp_sec }}.txt"
      run_once: true
      delegate_to: localhost

    - name: add SFTP server to inventory
      add_host:
        name: sftp_target  
        ansible_host: "{{ sftp_host }}"
        ansible_user: "{{ sftp_username }}"
        ansible_ssh_pass: "{{ sftp_password }}"
        ansible_connection: ssh
        ansible_ssh_common_args: >
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
      run_once: true
      no_log: true
      delegate_to: localhost

    - name: Create backup folder
      ansible.builtin.file:
        path: "{{ sftp_path }}/{{ timestamp_day }}"
        state: directory
        mode: '0755'
      run_once: true
      delegate_to: sftp_target

    - name: upload to SFTP
      copy:
        src: "/tmp/show_output_{{ timestamp_sec }}.txt"
        dest: "{{ sftp_path }}/show_output_{{ timestamp_sec }}.txt"
        mode: "0444"
      delegate_to: sftp_target 
# No native SFTP in Ansible. Use shell fallback below if needed.
#      shell: |
#        sshpass -p "{{ sftp_password }}" sftp -o StrictHostKeyChecking=no -P {{ sftp_port | default(22) }} {{ sftp_username }}@{{ sftp_host }} <<EOF
#        cd ansible
#        put /tmp/show_output_{{ timestamp_sec }}.txt 
#        bye
#        EOF
#      delegate_to: localhost
      run_once: true
      no_log: false

    - name: delete tmp file
      file:
        path: "/tmp/show_output_{{ timestamp_sec }}.txt"
        state: absent
      run_once: true
      delegate_to: localhost
