- name: Lookup host id (should exist after upsert)
  uri:
    url: "{{ controller_host }}/api/v2/hosts/?name={{ row.name }}&inventory={{ inventory_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Accept: "application/json"
    validate_certs: no
    return_content: yes
    status_code: 200
  register: host_lookup
  run_once: true
  no_log: true

- name: Get current groups for this host
  uri:
    url: "{{ controller_host }}/api/v2/hosts/{{ host_lookup.json.results[0].id }}/groups/"
    headers:
      Authorization: "Bearer {{ controller_token }}"
    validate_certs: no
  register: current_groups
  run_once: true
  no_log: true

- name: Remove host from all current groups
  uri:
    url: "{{ controller_host }}/api/v2/groups/{{ item.id }}/hosts/"
    method: POST
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Content-Type: "application/json"
    validate_certs: no
    body_format: raw
    body: >-
      {{ {'id': host_lookup.json.results[0].id | int, 'disassociate': true} | to_json }}
    status_code: [204, 400]
  loop: "{{ current_groups.json.results }}"
  run_once: true
  no_log: true

- name: Add host to groups listed in CSV
  uri:
    url: "{{ controller_host }}/api/v2/groups/{{ group_id }}/hosts/"
    method: POST
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Content-Type: "application/json"
      Accept: "application/json"
    validate_certs: no
    body_format: raw
    body: >-
      {{ {'id': host_lookup.json.results[0].id | int} | to_json }}
    status_code: [204, 400, 409]
  vars:
    g_clean: "{{ g | trim }}"
    api_url: "{{ controller_host }}/api/v2/groups/?name={{ g_clean }}&inventory={{ inventory_id }}"
    group_lookup: "{{ lookup('url', api_url, headers={'Authorization': 'Bearer ' ~ controller_token}, validate_certs=False) | from_json }}"
    group_id: "{{ group_lookup.results[0].id }}"
  loop: "{{ (row.groups | default('')).split(',') }}"
  loop_control:
    loop_var: g
  when: g_clean != ""
  run_once: true
  no_log: false