---
- name: Create standard inventory groups
  uri:
    url: "{{ controller_host }}/api/v2/groups/"
    method: POST
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Content-Type: "application/json"
    validate_certs: no
    body_format: raw
    body: "{{ group_body | to_json }}"
    status_code: [201, 400]
  vars:
    group_body:
      name: "{{ item.name }}"
      inventory: "{{ inventory_id | int }}"
      variables: "{{ item.variables | default({}) | to_json}}"
  loop:
    - name: nxos
      variables:
        ansible_network_os: nxos
    - name: ios
      variables:
        ansible_network_os: ios
    - name: even
    - name: odd
#    - name: temp
  no_log: true

- name: Get all groups in inventory
  uri:
    url: "{{ controller_host }}/api/v2/groups/?inventory={{ inventory_id }}&page_size=200"
    headers:
      Authorization: "Bearer {{ controller_token }}"
    validate_certs: no
  register: groups_response
  no_log: true

- name: Build group_id_map
  set_fact:
    group_id_map: >-
      {{
        dict(
          groups_response.json.results | map(attribute='name') |
          zip(groups_response.json.results | map(attribute='id'))
        )
      }}