---
- name: Create standard inventory groups
  uri:
    url: "{{ controller_host }}/api/v2/groups/"
    method: POST
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Content-Type: "application/json"
    validate_certs: no
    body_format: raw
    body: >-
      {{
        {
          'name': item.name,
          'inventory': inventory_id | int,
          'variables': (item.variables | default({})) | to_json
        } | to_json
      }}
    status_code: [201, 400]
  loop: "{{ standard_groups }}"
  no_log: true
  run_once: true
  vars:
    standard_groups:
      - name: nxos
        variables:
          ansible_network_os: nxos
      - name: ios
        variables:
          ansible_network_os: ios
#      - name: eos
#        variables:
#          ansible_network_os: eos
      - name: even
      - name: odd
      - name: temp