- name: Lookup host id (should exist after upsert)
  uri:
    url: "{{ controller_host }}/api/v2/hosts/?name={{ row.name }}&inventory={{ inventory_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Accept: "application/json"
    validate_certs: no
    return_content: yes
    status_code: 200
  register: host_lookup
  run_once: true

- name: Lookup group ID
  set_fact:
    group_data: >-
      {{ lookup('url', 
         controller_host + '/api/v2/groups/?name=' + g_clean + '&inventory=' + (inventory_id | string),
         headers={'Authorization': 'Bearer ' + controller_token},
         validate_certs=False) | from_json }}

- name: Add host to group
  uri:
    url: "{{ controller_host }}/api/v2/groups/{{ group_data.results[0].id }}/hosts/"
    method: POST
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Content-Type: "application/json"
    validate_certs: no
    body_format: json
    body:
      id: "{{ host_lookup.json.results[0].id | int }}"
    status_code: [204, 400, 409]
  loop: "{{ (row.groups | default('')).split(',') }}"
  loop_control:
    loop_var: g
  when: g != ""
  ignore_errors: yes
  run_once: true

- name: Debug actual request body
  debug:
    msg: "{{ {'id': (host_lookup.json.results[0].id | int)} }}"
