---
- import_tasks: t_time_stamp.yml
- name: interface status check before patch
  nxos_command:
    commands:
    - command: show interface status
  register: int_status_before

- name: interface status check before patch using json format
  nxos_command:
    commands:
    - command: show interface status up
      output: json
  register: int_status_before_json

- name: set filename for interface status
  set_fact:
    filename: "if_{{ ansible_network_hostname }}_{{ timestamp_sec }}.txt"

- name: save interface status to local file
  copy:
    content: "{{ int_status_before.stdout_lines[0] | join('\n') }}"
    dest: "/tmp/tmpfiles/{{ filename }}"

# Upload interface status to SFTP
- import_tasks: t_upload.yml
  vars:
    ansible_connection: ssh
- import_tasks: t_delete_file.yml

- import_tasks: t_check_md5.yml

- name: firmware upgrade
  nxos_install_os:
    system_image_file: '{{ firmware_filename }}'
    issu: no
  register: install_output
  vars:
    ansible_command_timeout: 600
    ansible_connect_timeout: 600
  ignore_errors: yes

- import_tasks: t_patch_confirm_nxos.yml
