---
- name: Disconnect from device
  meta: reset_connection

- name: Wait until ping fails (device going down)
  shell: "ping -c 1 -W 1 {{ ansible_host }}"
  retries: 30
  delay: 30
  until: ping_result.rc != 0
  ignore_errors: yes
  failed_when: false

- name: Wait until ping succeeds (device back up)
  shell: "ping -c 1 -W 1 {{ ansible_host }}"
  register: ping_result
  retries: 300
  delay: 10
  until: ping_result.rc == 0

#- name: Extra wait for TACACS
#  pause:
#    seconds: 30
- name: get expected version
  set_fact:
    file_version: "{{ firmware_filename | regex_search('(\\d+\\.\\d+\\.\\d+)') }}"
  run_once: true
  delegate_to: localhost
- name: get current OS version
  cli_command:
    command: "show version"
  register: version_outputs
  failed_when: file_version not in  version_outputs.stdout
- name: testest
  debug:
    msg:
      - "version:{{version_outputs.stdout}}"
      - "fileversion:{{  file_version  }}"
