---
#- name: Wait until ping fails (device going down)
#  shell: "ping -c 1 -W 1 {{ ansible_host }}"
#  register: ping_result
#  retries: 30
#  delay: 30
#  until: ping_result.rc != 0
#  failed_when: false

- name: Wait until ping succeeds (device back up)
  shell: "ping -c 1 -W 1 {{ ansible_host }}"
  register: ping_result
  retries: 300
  delay: 10
  until: ping_result.rc == 0

- name: Extra wait for TACACS
  pause:
    seconds: 30

#- name: get expected version
#  set_fact:
#    file_version: "{{ firmware_filename | regex_search('(\\d+\\.\\d+\\.\\d+)') }}"
#  run_once: true
#  delegate_to: localhost

#- name: get current OS version
#  nxos_command:
#    commands:
#    - command: show version
#      output: json
#  register: version_outputs
#  failed_when: firmware_filename not in version_outputs.stdout

- name: interface status check after patch
  nxos_command:
    commands:
    - command: show interface lo 0 status 
      output: json
  register: int_status_after_json

#- name: compare interface status
#  set_fact:
#    int_diff: "{{ int_status_before_json.stdout[0] | 
#                  difference(int_status_before_json.stdout[0]) }}"

- name: compare interface status
  fact_diff:
    before: "{{ int_status_before_json.stdout[0] }}"
    after: "{{ int_status_before_json.stdout[0] }}"
  register: int_diff
                  
- name: debug inter diff
  debug:
    msg: "{{ int_diff }}"

- name: debug int status before
  debug:
    msg: "{{ int_status_before_json }}"

- name: debug int status after
  debug:
    msg: "{{ int_status_after_json }}"

- name: append diff to log
  blockinfile:
    path: "/tmp/tmpfiles/patch_log.txt"
    block: |
      {{ ansible_network_hostname }}
      {{ int_diff }}
    insertafter: EOF
    create: yes
  delegate_to: localhost
  when: int_diff | length > 0

- name: set filename for interface status
  set_fact:
    filename: "patch_log.txt"

- import_tasks: tasks/t_upload.yml
  vars:
    ansible_connection: ssh
  when: int_diff | length > 0

- name: check again after 60 secconds
  wait_for:
    timeout: 60
  delegate_to: localhost
  when: int_diff | length > 0

- name: recheck interface status
  nxos_command:
    commands:
    - command: show interface status
      output: json
  register: int_status_recheck
  when: int_diff | length > 0

- name: debug int status recheck
  debug:
    msg: "{{ int_status_recheck }}"

- name: set recheck diff
  set_fact:
    int_diff_recheck: "{{ int_status_before_json.stdout[0] | 
                  difference(int_status_recheck.stdout[0]) }}"
  when: int_diff | length > 0

- name: fail if still different
  fail:
    msg: "Interface diff still exists after 60s: {{ int_diff_recheck }}"
  when:
    - int_diff | length > 0
    - int_diff_recheck | length > 0
