---
- name: Wait until ping fails (device going down)
  shell: "ping -c 1 -W 1 {{ ansible_host }}"
  register: ping_result
  retries: 30
  delay: 30
  until: ping_result.rc != 0
  failed_when: false

- name: Wait until ping succeeds (device back up)
  shell: "ping -c 1 -W 1 {{ ansible_host }}"
  register: ping_result
  retries: 30
  delay: 20
  until: ping_result.rc == 0

- name: Extra wait for TACACS
  pause:
    seconds: 30

- name: get current OS version
  nxos_command:
    commands:
    - command: show version
      output: json
  register: version_outputs
  failed_when: firmware_filename not in version_outputs.stdout[0].nxos_file_name

- name: debug before_json
  debug:
    msg: "{{ int_status_before_json }}"

- name: recheck interface status
  nxos_command:
    commands:
    - command: show interface status up
      output: json
  register: int_status_after_json
  retries: 16
  delay: 30
  until: >
    int_status_before_json.stdout[0].TABLE_interface.ROW_interface 
    == int_status_after_json.stdout[0].TABLE_interface.ROW_interface
  failed_when: false

- name: compare interface status
  set_fact:
    int_diff: "{{ int_status_before_json.stdout[0].TABLE_interface.ROW_interface | 
                  difference(int_status_after_json.stdout[0].TABLE_interface.ROW_interface) }}"

- name: show interface that is not up
  debug:
    msg: "{{  int_diff  }}"
  when: int_diff | length > 0

- name: append diff to log
  shell: |
    echo "{{ ansible_network_hostname }} below interface status changed during upgrade" >> /tmp/tmpfiles/patch_log.txt
    {% for intf in int_diff %}
    echo "{{ intf.interface }}" >> /tmp/tmpfiles/patch_log.txt
    {% endfor %}
  delegate_to: localhost
  when: int_diff | length > 0

- name: set file name for SFTP upload
  set_fact:
    filename: patch_log.txt
  when: int_diff | length > 0

- import_tasks: t_upload.yml
  vars:
    ansible_connection: ssh
  when: int_diff | length > 0

- name: fail if interface not recovered within 8 minutes
  fail:
    msg: "those interface are down after patch: {{ int_diff }}"
  when: int_diff | length > 0
