---
- name: firmware upgrade
  cli_command:
    command: "install all nxos bootflash:{{ firmware_filename }} non-interruptive"
#    command: "reload"
  async: 100
  poll: 10
  ignore_errors: yes
  register: install_output
