---
- name: "iosxe Remove inactive install packages"
  cli_command:
    command: "install remove inactive"
    prompt: 'Do you want to remove the above files\?'
    answer: "y"
  vars:
    ansible_command_timeout: 300
  register: clean_output

- name: "[iosxe] Debug cleanup result"
  debug:
    msg: "{{ clean_output.stdout }}"
