---
- name: Disconnect from device
  meta: reset_connection

- name: Wait for device to go offline
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    state: stopped
    timeout: 180
    sleep: 10
  delegate_to: localhost
  register: went_down
  
- name: Waiting For SSH port responsible
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    timeout: 600
    delay: 100 
    sleep: 15
  delegate_to: localhost

- name: Extra wait for TACACS
  pause:
    seconds: 30
    
- name: get current OS version
  cli_command:
    command: "show version"
  register: version_outputs
  failed_when: file_version not in  version_outputs.stdout
