---
- name: firmware upgrade
  vars:
    ansible_command_timeout: 900
  cli_command:
    command: "install add file flash:{{ firmware_filename }} activate commit prompt-level none"
  async: 60
  poll: 0
  ignore_errors: yes
  register: install_output
