---
- name: wait before recheck
  wait_for:
    timeout: 3
  delegate_to: localhost
  
- name: interface status check after patch
  nxos_command:
    commands:
    - command: show interface status up
      output: json
  register: int_status_after_json

- name: compare interface status
  set_fact:
    int_diff: "{{ int_status_before_json.stdout[0].TABLE_interface.ROW_interface | 
                  difference(int_status_after_json.stdout[0].TABLE_interface.ROW_interface) }}"

- name: show interface that is not up
  debug:
    msg: "{{  int_diff  }}"

- name: append diff to log
  shell: |
    echo "{{ ansible_network_hostname }} below interface status changed during upgrade" >> /tmp/tmpfiles/patch_log.txt
    {% for intf in int_diff %}
    echo "{{ intf.interface }}" >> /tmp/tmpfiles/patch_log.txt
    {% endfor %}
  delegate_to: localhost
  when: int_diff | length > 0

- name: increment counter
  set_fact:
    retry_count: "{{ retry_count | int + 1 }}"
    
# recheck again for 8 minutes
#- import_tasks: tasks/t_patch_if_check_nxos.yml
#  when: retry_count | int < 16 and int_diff | length > 0

