---
- name: firmware upgrade
  vars:
   ansible_command_timeout: 900
   patch_commands:
     ios: "install add file flash:{{ firmware_filename }} activate commit prompt-level none"
#     nxos: "install all nxos bootflash:{{  firmware_filename  }} non-interruptive"
     nxos: "show install all impact nxos bootflash:{{  firmware_filename  }}"
  cli_command:
    command: "{{ patch_commands[ansible_network_os] }}"
  async: 60
  poll: 0
  ignore_errors: yes
  register: install_output
