---
#- name: Wait until ping fails (device going down)
#  shell: "ping -c 1 -W 1 {{ ansible_host }}"
#  register: ping_result
#  retries: 30
#  delay: 30
#  until: ping_result.rc != 0
#  failed_when: false

- name: Wait until ping succeeds (device back up)
  shell: "ping -c 1 -W 1 {{ ansible_host }}"
  register: ping_result
  retries: 300
  delay: 10
  until: ping_result.rc == 0

- name: Extra wait for TACACS
  pause:
    seconds: 30

#- name: get expected version
#  set_fact:
#    file_version: "{{ firmware_filename | regex_search('(\\d+\\.\\d+\\.\\d+)') }}"
#  run_once: true
#  delegate_to: localhost

- name: get current OS version
  nxos_command:
    commands:
    - command: show version
      output: json
  register: version_outputs
  failed_when: firmware_filename not in version_outputs.stdout[0].nxos_file_name

- name: increment counter
  set_fact:
    retry_count: 0
    int_diff: []

- include_tasks: tasks/t_patch_if_check_nxos.yml

- name: fail if interface not recovered within 8 minutes
  fail:
    msg: "those interface are down after patch: {{ int_diff }}"
  when: retry_count | int >= 16 and int_diff | length > 0
