---
- name: add SFTP server to inventory
  add_host:
    name: sftp_target
    group: temp
    ansible_host: "{{ sftp_host }}"
    ansible_user: "{{ sftp_username }}"
    ansible_ssh_pass: "{{ sftp_password }}"
    ansible_connection: ssh
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
  no_log: true
  delegate_to: localhost
  run_once: true