---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: generate time stamp
      set_fact:
        timestamp: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d-%H%M%S') }}"
      run_once: true
      delegate_to: localhost
      
    - name: run defined command from Extra variables
      ansible.netcommon.cli_backup:
        filename: {{ ansible_network_hostname }}_{{ timestamp }}.txt
        dir_path: /tmp/backup/
      register: backup_outputs
      
    - name: show result
      debug:
        msg: "{{ backup_outputs }}"
      
#    - name: create output file locally
#      copy:
#        cli_outputs.results.stdout
#        dest: "/tmp/{{ ansible_network_hostname }}_{{ timestamp }}.txt"
#      run_once: true
#      delegate_to: localhost
