---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: generate time stamp
      set_fact:
        timestamp_day: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d') }}"
        timestamp_sec: "{{ lookup('pipe','TZ=America/New_York date +%H%M%S') }}"
      run_once: true
      delegate_to: localhost
      
    - name: run backup
      cli_config:
        backup: "yes"
        backup_options:
          filename: "{{ ansible_network_hostname | default(inventory_hostname) }}_{{ timestamp_sec }}.txt"
          dir_path: "/tmp/tmpfiles"
      register: backup_outputs
      
    - name: show result
      debug:
        msg: "{{ backup_outputs }}"

    - name: add SFTP server to inventory
      add_host:
        name: sftp_target  
        ansible_host: "{{ sftp_host }}"
        ansible_user: "{{ sftp_username }}"
        ansible_ssh_pass: "{{ sftp_password }}"
        ansible_connection: ssh
        ansible_ssh_common_args: >
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
      run_once: true
      no_log: true
      delegate_to: localhost

    - name: Create backup folder
      ansible.builtin.file:
        path: "{{ sftp_path }}/{{ timestamp_day }}"
        state: directory
        mode: '755'
      run_once: true
      delegate_to: sftp_target

    - name: upload to SFTP
      copy:
        src: "/tmp/tmpfiles/{{ ansible_network_hostname | default(inventory_hostname) }}_{{ timestamp_sec }}.txt"
        dest: "{{ sftp_path }}/{{ timestamp_day }}/{{ ansible_network_hostname | default(inventory_hostname) }}_{{ timestamp_sec }}.txt"
        mode: "0444"
      delegate_to: sftp_target
      no_log: flase

    - name: delete tmp file
      file:
        path: "/tmp/tmpfiles/{{ ansible_network_hostname | default(inventory_hostname) }}_{{ timestamp_sec }}.txt"
        state: absent
      delegate_to: localhost
