---
- name: upload firmware
  hosts: all
  gather_facts: no
  
  tasks:
    - name: generate time stamp
      set_fact:
        timestamp: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d') }}"
      run_once: true
      delegate_to: localhost

    - name: add SFTP server to inventory
      add_host:
        name: sftp_target  
        ansible_host: "{{ sftp_host }}"
        ansible_user: "{{ sftp_username }}"
        ansible_ssh_pass: "{{ sftp_password }}"
        ansible_connection: ssh
        ansible_ssh_common_args: >
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
      run_once: true
      no_log: true
      delegate_to: localhost

    - debug: 
        msg: "user={{ ansible_user }} pass={{ ansible_password }}"

      
    - name: Download firmware from SFTP host to controller
      ansible.builtin.fetch:
        src: "{{ sftp_path }}/{{ firmware }}"
        dest: "/tmp/{{ firmware }}"
        flat: true
      delegate_to: sftp_target
      run_once: true

    - name: Upload firmware to switch
      ansible.builtin.command: >
        scp -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
            -p '{{ ansible_password }}'
            /tmp/{{ firmware }}
            {{ ansible_user }}@{{ inventory_hostname }}:

    - name: delete tmp file
      file:
        path: "/tmp/{{ firmware }}"
        state: absent
      run_once: true
      delegate_to: localhost
