---
- name: upload firmware
  hosts: all
  gather_facts: no
  ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  
  tasks:
    - name: generate time stamp
      set_fact:
        timestamp: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d') }}"
      run_once: true
      delegate_to: localhost

    - name: add SFTP server to inventory
      add_host:
        name: sftp_target  
        ansible_host: "{{ sftp_host }}"
        ansible_user: "{{ sftp_username }}"
        ansible_ssh_pass: "{{ sftp_password }}"
        ansible_connection: ssh
      run_once: true
      no_log: true
      delegate_to: localhost
      
    - name: Download firmware from SFTP host to controller
      ansible.builtin.fetch:
        src: "{{ sftp_path }}/{{ timestamp }}/{{ firmware }}"
        dest: "/tmp/{{ firmware }}"
        flat: true
      delegate_to: sftp_target
      run_once: true
      no_log: true

    - name: Upload firmware to switch
      ansible.netcommon.net_put:
        src: "/tmp/{{ firmware }}"
        dest: "{{ firmware }}"   # e.g. "bootflash:/{{ firmware }}" or "flash:/{{ firmware }}"
        protocol: scp
