---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: generate time stamp
      set_fact:
        timestamp: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d-%H%M%S') }}"
      run_once: true
      delegate_to: localhost
      
    - name: run defined command from Extra variables
      cli_command:
        command: "show running-configure"
      register: cli_outputs
      
    - name: show result
      debug:
        msg: "{{ cli_outputs }}"
      
    - name: create output file locally
      copy:
        cli_outputs.results.stdout
        dest: "/tmp/{{ ansible_network_hostname }}_{{ timestamp }}.txt"
      run_once: true
      delegate_to: localhost
