---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: generate time stamp
      set_fact:
        timestamp: "{{ lookup('pipe','date +%Y%m%d-%H%M%S') }}"
      run_once: true
      delegate_to: localhost

    - name: run defined command from Extra variables
      cli_command:
        command: "{{ item }}"
      loop: "{{ cli_cmd }}"
      register: cli_outputs
      
    - name: show result
      debug:
        msg: "{{ cli_outputs }}"
        
    - name: create output file locally
      copy:
        content: |
          =================================================
          Host: {{ inventory_hostname }}
          OS: {{ ansible_network_os | default('unknown') }}
          time: {{ timestamp }}
          {% for result in cli_outputs.results %}
          ----------------------------------------
          Command {{ loop.index }}: {{ result.item }}
          ----------------------------------------
          {{ result.stdout_lines | join('\n')}}      
          {% endfor %}
          ========================================
        dest: "/tmp/output_{{ timestamp }}.txt"
      delegate_to: localhost
      
    - name: upload to SFTP via SCP
      shell: >
        sshpass -p "{{ sftp_password }}" 
        scp -P {{ sftp_port | default(22) }} 
        -o StrictHostKeyChecking=no 
        /tmp/output_{{ timestamp }}.txt 
        {{ sftp_username }}@{{ sftp_host }}:/upload/from_ansible/output_{{ timestamp }}.txt
      delegate_to: localhost
      no_log: true

#    - name: #delete tmp file
#      file:
#        path: "/tmp/output_{{ timestamp }}.txt"
#        state: absent
#      delegate_to: localhost
