---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run defined command from Extra variables #using 'ansible_network_os' field in inventory to determine device's OS
      block:
        - ios_command:
           commands: "{{ cli_cmd }}" #using the 'EXTRA AVARIABLES' filed in template for the command to run
          register: cli_output
          when: ansible_network_os == 'ios'

        - nxos_command:
            commands: "{{ cli_cmd }}"
          register: cli_output
          when: ansible_network_os == 'nxos'

        - eos_command:
            commands: "{{ cli_cmd }}"
          register: cli_output
          when: ansible_network_os == 'eos'
    - name: show result
      debug:
        var: cli_output.stdout
    - name: create output file locally
      copy:
        content: |
          output: {{ cli_output.stdout }}
          job_time: {{ ansible_date_time.iso8601 }}
      dest: "/tmp/output_{{ lookup('pipe','date +%Y%m%d-%H%M%S')}}.txt"
      delegate_to: localhost           
    - name: upload to SFTP 
      net_tools.sftp.sftp:
        mode: put
        src: "/tmp/output_{{ lookup('pipe','date +%Y%m%d-%H%M%S')}}.txt"
        dest: "/upload/from_ansible/output_{{ lookup('pipe','date +%Y%m%d-%H%M%S')}}.txt"
        host: "{{ sftp_host }}"
        port: "{{ sftp_port | default(22) | int }}"
        username: "{{ sftp_username }}"
        password: "{{ sftp_password }}"
      delegate_to: localhost
