---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: generate time stamp
      set_fact:
        now: "{{ lookup('pipe','TZ=America/New_York date \"+%Y-%m-%d %H:%M:%S\"') }}"
        timestamp: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d-%H%M%S') }}"
      run_once: true
      delegate_to: localhost

    - name: run defined command from Extra variables
      cli_command:
        command: "{{ item }}"
      loop: "{{ cli_cmd }}"
      register: cli_outputs
        
    - name: show result
      debug:
        msg: "{{ cli_outputs }}"

    - name: create output file locally
      copy:
        content: |
          =================================================
          Network Command Output Report
          Generated: {{ now }}
          Total Hosts: {{ ansible_play_hosts | length }}
          =================================================
          
          {% for host in ansible_play_hosts %} 

          =================================================
          IP: {{ host }}
          Hostname: {{ hostvars[host].ansible_network_hostname | default(host) }}
          {% for result in hostvars[host].cli_outputs.results %} 
          ----------------------------------------
          Command {{ loop.index }}: {{ result.item }}
          ----------------------------------------
          {{ result.stdout }}      
          {% endfor %}
          {% endfor %}
          ========================================
        dest: "/tmp/show_output_{{ timestamp }}.txt"
      run_once: true
      delegate_to: localhost

    - name: upload to SFTP
      copy:
        src: "/tmp/show_output_{{ timestamp }}.txt"
        dest: "ansible/show_output_{{ timestamp }}.txt"
      delegate_to: "{{ sftp_host }} " 
#      shell: |
#        sshpass -p "{{ sftp_password }}" sftp -o StrictHostKeyChecking=no -P {{ sftp_port | default(22) }} {{ sftp_username }}@{{ sftp_host }} <<EOF
#        cd ansible
#        put /tmp/show_output_{{ timestamp }}.txt 
#        bye
#        EOF
      run_once: true
      # delegate_to: localhost
      no_log: no

    - name: delete tmp file
      file:
        path: "/tmp/show_output_{{ timestamp }}.txt"
        state: absent
      run_once: true
      delegate_to: localhost
