---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: generate time stamp
      set_fact:
        timestamp: "{{ lookup('pipe','date +%Y%m%d-%H%M%S') }}"
      run_once: true
      delegate_to: localhost

    - name: run defined command from Extra variables
      cli_command:
        command: "{{ item }}"
      loop: "{{ cli_cmd }}"
      register: cli_output

    - name: show result
      debug:
        msg: "{{ cli_output.stdout_lines[0] | default('error') }}"

    - name: create output file locally
      copy:
        content: |
          Host: {{ inventory_hostname }}
          OS: {{ ansible_network_os | default('unknown') }}
          Command: "{{ cli_cmd }}"
          Output: {{ cli_output.stdout_lines[0] | default('error') }}
          Job time: {{ timestamp }}
        dest: "/tmp/output_{{ timestamp }}.txt"
      delegate_to: localhost

#    - name: upload to SFTP
#      net_tools.sftp.sftp:
#        mode: put
#        src: "/tmp/output_{{ timestamp }}.txt"
#        dest: "/upload/from_ansible/output_{{ timestamp }}.txt"
#        host: "{{ sftp_host }}"
#        port: "{{ sftp_port | default(22) | int }}"
#        username: "{{ sftp_username }}"
#        password: "{{ sftp_password }}"
#      delegate_to: localhost
#
#    - name: #delete tmp file
#      file:
#        path: "/tmp/output_{{ timestamp }}.txt"
#        state: absent
#      delegate_to: localhost
