---
- name: run cli command (Multiple vendor supports)
  hosts: all
  gather_facts: yes
  connection: network_cli

  tasks:
    - name: generate time stamp
      set_fact:
        timestamp: "{{ lookup('pipe','date +%Y%m%d-%H%M%S') }}"
      run_once: true
      delegate_to: localhost

    - name: run defined command from Extra variables
      cli_command:
        command: "{{ item }}"
      loop: "{{ cli_cmd }}"
      register: cli_outputs
            
    - name: show result
      debug:
        msg: "{{ cli_outputs }}"
        
    - name: create output file locally
      copy:
        content: |
          =================================================
          Network Command Output Report
          Generated: {{ timestamp }}
          Total Hosts: {{ ansible_play_hosts | length }}
          =================================================
          {% for host in ansible_play_hosts %}

          =================================================
          IP: {{ host }}
          Hostname: {{ansible_net_hostname }}
          OS: {{ ansible_net_iostype }}
          {% for result in cli_outputs.results %}
          ----------------------------------------
          Command {{ loop.index }}: {{ result.item }}
          ----------------------------------------
          {{ result.stdout}}      
          {% endfor %}
          {% endfor %}
          ========================================
        dest: "/tmp/ansible_show_output_{{ timestamp }}.txt"
      delegate_to: localhost
      
#    - name: upload to SFTP
#      shell: |
#        sshpass -p "{{ sftp_password }}" sftp -o StrictHostKeyChecking=no -P {{ sftp_port | default(22) }} {{ sftp_username }}@{{ sftp_host }} <<EOF
#        cd ansible
#        put /tmp/output_{{ timestamp }}.txt 
#        bye
#        EOF
#      delegate_to: localhost
#      no_log: true

#    - name: delete tmp file
#      file:
#        path: "/tmp/output_{{ timestamp }}.txt"
#        state: absent
#      delegate_to: localhost
