---
- name: Generate timestamp once
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate time stamp
      set_stats:
        data:
          timestamp_day: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d') }}"
          timestamp_sec: "{{ lookup('pipe','TZ=America/New_York date +%H%M%S') }}"
