- name: Generate timestamp once and store globally
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create global vars host
      add_host:
        name: GLOBAL_VARS
        groups: global_vars
        timestamp_day: "{{ lookup('pipe','TZ=America/New_York date +%Y%m%d') }}"
        timestamp_sec: "{{ lookup('pipe','TZ=America/New_York date +%H%M%S') }}"
